version: '3.4'


services:
  imdb.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
  imbd.db:
    image: mcr.microsoft.com/mssql/server:2022
    container_name: imdb.db
    environment:
      - name=value
    volumes:
      - ./.containers/imdb-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  imdb.cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

